Repository UCF/Main-Site-Theme, pull requests merged in 2019-11, with the labels that each got.

#198 Added aria-hidden to media background video elems
  functions.php
Labels: accessibility

#197 Location map title
  single-location.php
Labels: accessibility

#199 Corrected bug that causees incorrect grouping of results
  includes/phonebook-functions.php
Labels: bug

#200 Adjustments to Phonebook Results Layout/Styles
  includes/phonebook-functions.php
  src/scss/pages/_phonebook.scss
  static/css/style.min.css
Labels: enhancement

#201 Update phonebook result column widths
  includes/phonebook-functions.php
Labels: enhancement
