Repository UCF/Main-Site-Theme, pull requests merged in 2022-03, with the labels that each got.

#393 Accessibility Updates to Degree Profile Templates
  template-parts/degree/course_overview.php
  template-parts/degree/program_at_a_glance.php
Labels: accessibility

#394 Add a phonebook exception for 'It'
  includes/phonebook-functions.php
Labels: bug

#397 Packages updates
  package-lock.json
  package.json
  src/scss/_degrees.scss
  src/scss/_header.scss
  src/scss/_variables.scss
  src/scss/components/_news.scss
  src/scss/pages/_degree-search.scss
  static/css/style.min.css
  static/js/degree-search-typeahead.min.js
  static/js/faculty-search-typeahead.min.js
  static/js/script.min.js
Labels: accessibility, dependencies

#400 Link underline cleanup
  functions.php
  includes/degree-search-functions.php
  src/scss/_degrees.scss
  src/scss/pages/_degree-search.scss
  static/css/style.min.css
  taxonomy-colleges.php
  template-parts/degree/course_overview.php
  template-parts/degree/news.php
Labels: enhancement, accessibility

#401 Assorted styling adjustments
  includes/location-functions.php
  single-location.php
  src/scss/_base.scss
  src/scss/_variables.scss
  src/scss/components/_news.scss
  src/scss/utils/_clip.scss
  static/css/style.min.css
  taxonomy-colleges.php
Labels: bug, enhancement

#402 Remove statements functions, config options, and template
  functions.php
  includes/config.php
  includes/statements-functions.php
  template-statements.php
Labels: bug

#403 Remove underline from the A-Z Index 'Back to Top' link
  src/scss/pages/_a-z-index.scss
  static/css/style.min.css
Labels: enhancement, accessibility

#404 Colleges - added option to split top degrees and custom degree lists; other housecleaning things
  dev/acf-export.json
  functions.php
  includes/college-functions.php
  taxonomy-colleges.php
Labels: enhancement, accessibility

#407 p-p-p-packages
  package-lock.json
  package.json
  static/css/style.min.css
Labels: accessibility
