Repository UCF/Main-Site-Theme, pull requests merged in 2025-07, with the labels that each got.

#505 Empty Custom Descriptions
  includes/degree-import-functions.php
Labels: bug

#506 Instruction for header image.
  dev/acf-export.json
Labels: enhancement

#507 Modal opens when the URL hash is #requestInfoModal
  src/js/degree-page.js
  static/css/style.min.css
  static/js/degree-page.min.js
Labels: bug, enhancement

#508 Onload, catalog modal will be opened.
  src/js/degree-page.js
  static/js/degree-page.min.js
Labels: enhancement
