Repository UCF/Main-Site-Theme, pull requests merged in 2025-08, with the labels that each got.

#511 Updated college_url_clean to correct syntax error
  includes/degree-functions.php
Labels: bug

#513 Added the sharp fonts icons to font awesome subset.
  gulpfile.js
  src/scss/_fontawesome-pro.scss
  static/css/style.min.css
  static/fonts/font-awesome-pro/fa-sharp-light-300.ttf
  static/fonts/font-awesome-pro/fa-sharp-light-300.woff2
  static/fonts/font-awesome-pro/fa-sharp-regular-400.ttf
  static/fonts/font-awesome-pro/fa-sharp-regular-400.woff2
  static/fonts/font-awesome-pro/fa-sharp-solid-900.ttf
  static/fonts/font-awesome-pro/fa-sharp-solid-900.woff2
  static/fonts/font-awesome-pro/fa-sharp-thin-100.ttf
  static/fonts/font-awesome-pro/fa-sharp-thin-100.woff2
Labels: dependencies

#514 removed the sharp icons from fontawesome subset.
  gulpfile.js
  src/scss/_fontawesome-pro.scss
  static/css/style.min.css
  static/fonts/font-awesome-pro/fa-sharp-light-300.ttf
  static/fonts/font-awesome-pro/fa-sharp-light-300.woff2
  static/fonts/font-awesome-pro/fa-sharp-regular-400.ttf
  static/fonts/font-awesome-pro/fa-sharp-regular-400.woff2
  static/fonts/font-awesome-pro/fa-sharp-solid-900.ttf
  static/fonts/font-awesome-pro/fa-sharp-solid-900.woff2
  static/fonts/font-awesome-pro/fa-sharp-thin-100.ttf
  static/fonts/font-awesome-pro/fa-sharp-thin-100.woff2
Labels: dependencies

#517 Adding the title to degree description modal
  template-parts/degree/catalog_modal.php
Labels: enhancement
